# Generated by Django 4.1 on 2022-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
